# WHY NUMPY

Faster to read less bytes of memory
Ploting (MATPLOTLIB)
Backend (Pandas)
Machine Learning

In [178]:
#import numpy library
import numpy as np

In [179]:
# 1 dimensional
a = np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [180]:
# 2 dimensional
b = np.array([[9.0,8.0,5.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 5.]
 [6. 5. 4.]]


In [181]:
# Get dimension
a.ndim

1

In [182]:
b.ndim

2

In [183]:
# Get Shape
a.shape

(3,)

In [184]:
b.shape

(2, 3)

In [185]:
# Get Type
a.dtype

dtype('int16')

In [186]:
b.dtype

dtype('float64')

In [187]:
# Get size
a.itemsize

2

In [188]:
b.itemsize

8

In [189]:
# Get Total size
a.size

3

In [190]:
b.size

6

# Accessing/Changing specific elements, rows , columns etc..

In [191]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [192]:
a.shape

(2, 7)

In [193]:
a.ndim

2

In [194]:
# Get specific elements [r,c]
a[1,5]

13

In [195]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [196]:
# Get specific columns
a[:,2]

array([ 3, 10])

In [197]:
# Get elements between [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [198]:
a[0,1:6]

array([2, 3, 4, 5, 6])

In [199]:
# Changing values
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [200]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [201]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [202]:
# 3 dimension examples
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [203]:
# Get specific elements
b[0,1,:]

array([3, 4])

In [204]:
b[0,1,1]

4

In [205]:
# replace
b[:,1,:]=[[9,9],[9,9]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


In [206]:
# All 0s matrix
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [207]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [208]:
# Add any number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [209]:
# Any other number like copying size of other array (full_like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [210]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.87117107, 0.97940664, 0.48913829],
        [0.87772324, 0.85326067, 0.69543994]],

       [[0.08751608, 0.16714835, 0.45628458],
        [0.60924635, 0.40126294, 0.24073859]],

       [[0.58792814, 0.20865435, 0.77702025],
        [0.82882304, 0.42384804, 0.41636769]],

       [[0.25283615, 0.20509408, 0.08379391],
        [0.54533257, 0.93069453, 0.48719385]]])

In [211]:
# random number on shape of other array 
np.random.random_sample(a.shape)

array([[0.34783184, 0.42352367, 0.26697027, 0.54943908, 0.33846392,
        0.39404578, 0.90758041],
       [0.68985606, 0.7733515 , 0.45377731, 0.08769669, 0.68314572,
        0.69819785, 0.7259528 ]])

In [212]:
# Random integer values
np.random.randint(4,7,size=(3,3))

array([[4, 5, 4],
       [4, 6, 6],
       [6, 6, 5]])

In [213]:
# Random integer values
np.random.randint(7,size=(3,3))

array([[4, 2, 2],
       [1, 3, 0],
       [6, 6, 2]])

In [214]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [215]:
# repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [216]:
# repeat array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [217]:
# Example problem on merging different array

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be carefull while copying array

In [218]:
a = np.array([1,2,3])

b = a
print(b)

b[0] = 100

print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]


In [219]:
# use copy to prevent it
a = np.array([1,2,3])

b = a.copy()
print(b)

b[0] = 100

print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


#### Mathematics

In [220]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [221]:
a +=1
print(a)

[2 3 4 5]


In [222]:
a - 2

array([0, 1, 2, 3])

In [223]:
a*2

array([ 4,  6,  8, 10])

In [224]:
a / 2

array([1. , 1.5, 2. , 2.5])

In [225]:
a**2

array([ 4,  9, 16, 25])

In [226]:
b = np.array([1,0,1,0])
a+b

array([3, 3, 5, 5])

In [227]:
# Take the sin
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [228]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

#### Linear Algebra

In [229]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [230]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [231]:
# Matrix multiplication function
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [232]:
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [233]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [234]:
np.min(stats,axis=0)

array([1, 2, 3])

In [235]:
np.max(stats,axis=1)

array([3, 6])

In [236]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [237]:
np.sum(stats)

21

In [238]:
np.sum(stats,axis=1)

array([ 6, 15])

#### Reorganising arrays

In [239]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [240]:
after = before.reshape(8,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


####  Vertically stacking vectors

In [241]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

# Miscellaneous

#### Load data from File

In [242]:
filedata = np.genfromtxt('numpyexample.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean masking and Advanced indexing

In [243]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [244]:
filedata < 50

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [245]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [246]:
filedata[filedata < 50]

array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1], dtype=int32)

In [247]:
np.any(filedata > 50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [248]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [249]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])