In [6]:
import numpy as np
a=np.array([[1,2,3],[2,2,3]],dtype='int32')
a.dtype

dtype('int32')

In [5]:
a.shape

(2, 3)

In [7]:
a.ndim

2

In [8]:
a.itemsize

4

In [9]:
a.nbytes

24

In [11]:
a.reshape(3,2)

array([[1, 2],
       [3, 2],
       [2, 3]], dtype=int32)

In [13]:
b=np.array([[5,6,4],[7,8,78]])
a*b

array([[  5,  12,  12],
       [ 14,  16, 234]])

In [15]:
a[1,2]

3

In [16]:
a[0,:]

array([1, 2, 3], dtype=int32)

In [18]:
a[:,1]

array([2, 2], dtype=int32)

In [22]:
a[0,0:2:2]

array([1], dtype=int32)

In [24]:
a[1,2]=10
a

array([[ 1,  2,  3],
       [ 2,  2, 10]], dtype=int32)

In [28]:
a[:,2]=[1,2]
a

array([[1, 2, 1],
       [2, 2, 2]], dtype=int32)

In [29]:
a[:,2]=5
a

array([[1, 2, 5],
       [2, 2, 5]], dtype=int32)

In [38]:
b=np.array([[[1,2],[5,9]],[[4,7],[2,4]],[[7,8],[5,6]]],dtype='int16')
b

array([[[1, 2],
        [5, 9]],

       [[4, 7],
        [2, 4]],

       [[7, 8],
        [5, 6]]], dtype=int16)

In [40]:
b.shape

(3, 2, 2)

In [44]:
b[1,1,1]

4

In [57]:
b[:1,1,1:]=5
b

array([[[1, 2],
        [5, 5]],

       [[4, 7],
        [5, 5]],

       [[7, 8],
        [5, 5]]], dtype=int16)

In [62]:
b[:,1,:]=[9,9],[8,8],[6,7]
b

array([[[1, 2],
        [9, 9]],

       [[4, 7],
        [8, 8]],

       [[7, 8],
        [6, 7]]], dtype=int16)

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.ones([4,2,2,1],dtype='int32')

array([[[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]],


       [[[1],
         [1]],

        [[1],
         [1]]]], dtype=int32)

In [66]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [68]:
np.full_like(a.shape,4)

array([4, 4])

In [72]:
np.random.random_sample(a.shape)

array([[0.22509686, 0.39397075, 0.45661417],
       [0.57541531, 0.17814729, 0.56161842]])

In [73]:
np.random.rand(4,2)

array([[0.14926809, 0.67288582],
       [0.63352821, 0.35279967],
       [0.75749232, 0.69628043],
       [0.83905799, 0.38233397]])

In [80]:
np.random.randint(-2,5,size=(3,3))

array([[ 3,  4,  2],
       [ 2, -2,  1],
       [ 1, -1,  4]])

In [87]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [95]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [102]:
output=np.ones((5,5))
print(output)
               
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z     
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [109]:
a=np.array([4,5,4])
b=a.copy()
print(b)

[4 5 4]


In [110]:
b[0]=100
print(b)

[100   5   4]


In [111]:
print(a)

[4 5 4]


In [112]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [113]:
a+2

array([3, 4, 5, 6])

In [114]:
a-2

array([-1,  0,  1,  2])

In [115]:
a*2

array([2, 4, 6, 8])

In [116]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [120]:
b=np.array([5,4,7,7])

In [121]:
a+b

array([ 8,  8, 12, 13])

In [122]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [123]:
######LINEAR ALGEBRA

In [128]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [129]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [146]:
stat=np.array([[7,2,3],[4,5,4]])
stat

array([[7, 2, 3],
       [4, 5, 4]])

In [131]:
np.min(stat)

1

In [132]:
np.max(stat)

5

In [147]:
np.max(stat,axis=0)

array([7, 5, 4])

In [144]:
np.sum(stat,axis=1)

array([ 6, 13])

In [154]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.reshape(4,2,1))

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [155]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [157]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [161]:
filedata=np.genfromtxt('/home/praveen/Downloads/nba.csv',delimiter=',')
filedata.astype('int32')

array([[-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648],
       [-2147483648, -2147483648,           0, ...,         180,
        -2147483648,     7730337],
       [-2147483648, -2147483648,          99, ...,         235,
        -2147483648,     6796117],
       ...,
       [-2147483648, -2147483648,          21, ...,         256,
        -2147483648,     2900000],
       [-2147483648, -2147483648,          24, ...,         231,
        -2147483648,      947276],
       [-2147483648, -2147483648, -2147483648, ..., -2147483648,
        -2147483648, -2147483648]], dtype=int32)

In [162]:
filedata>50

/home/praveen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False,  True],
       [False, False,  True, ...,  True, False,  True],
       ...,
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True],
       [False, False, False, ..., False, False, False]])

In [163]:
a=np.array([1,2,3,4,5,6,7,8])
a[[1,2,3]]

array([2, 3, 4])

In [164]:
((filedata>50) & (filedata<100))

/home/praveen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.
/home/praveen/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])